# src/Acme/DemoBundle/Resources/config/services.yml
services:
#    acme_demo.example:
#        class: Acme\DemoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
# src/Acme/UserBundle/Resources/config/services.yml

 #   acme_user.password_resetting:
  #      class: Acme\DemoBundle\EventListener\PasswordResettingListener
  #      arguments: [@router]
  #      tags:
  #          - { name: kernel.event_subscriber }