Acme\DemoBundle\Entity\Backend:
    type: entity
    table: backend
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        conference_id:
            type: integer
           
          
            
             
    lifecycleCallbacks: {  }
