Acme\DemoBundle\Entity\Conference:
    type: entity
    table: conference
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        conferenceName:
            type: string
            length: '100'
        dueDate:
            type: datetime
        detail:
            type: text
            
        schedule:
            type: text
            
    oneToMany:
        signUps:
            targetEntity: SignUp
            mappedBy: conference
            
            
            
             
    lifecycleCallbacks: {  }
