Acme\DemoBundle\Entity\SignUp:
    type: entity
    repositoryClass: Acme\DemoBundle\Entity\Repository\SignUpRepository
    table: sign_up
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        signUpDate:
            type: datetime
            
    manyToOne:
        user:
            targetEntity: User
            inversedBy: signUps
            joinColumn:
                name: user_id
                referencedColumnName: id

        conference:
            targetEntity: Conference
            inversedBy: signUps
            joinColumn:
                name: conference_id
                referencedColumnName: id
                
    uniqueConstraints:
            sign_up_message:
                columns: user_id,conference_id
            
    lifecycleCallbacks: {  }
