Acme\DemoBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:          
        gender:
            type: string
            nullable: true
        company:
            type: string
            length: '100'  
            nullable: true
        position:
            type: string
            length: '100'   
            nullable: true
        address:
            type: string
            length: '100'   
            nullable: true
        phone:
            type: string
            length: '20' 
        name:
            type: string
            length: '20' 
        
    oneToMany:
        signUps:
            targetEntity: SignUp
            mappedBy: user
    