<?php

namespace Acme\DemoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Finder\Exception\AccessDeniedException;

/**
 * SignUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignUpRepository extends EntityRepository
{
    
    
    /**
     * 根据对应的会议和用户信息获取同一个学校的报名
     * 
     */
    public function querySignUpByUser($user, $conference){
      
      
        $params = array(
                'p1' => $conference ,
                'p2' => $user->getCompany()
            );
          return $this->getEntityManager()
            ->createQuery(
                'SELECT s ,u
                FROM AcmeDemoBundle:SignUp s 
                LEFT JOIN s.user u
                WHERE  s.conference=:p1 and u.company =:p2
                ORDER BY s.id ASC'
            )
            ->setParameters($params)
            ->getResult();
    }
    
        
        
        
        
 }