services:
#    acme_user.example:
#        class: Acme\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    acme_user.registration.form.type:
        class: Acme\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_registration }
            
    acme_user.profile.form.type:
        class: Acme\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_profile }
